// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// randles_fast_3d_rcpp
NumericMatrix randles_fast_3d_rcpp(const NumericMatrix& X, double tol);
RcppExport SEXP _RandlesID_randles_fast_3d_rcpp(SEXP XSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(randles_fast_3d_rcpp(X, tol));
    return rcpp_result_gen;
END_RCPP
}
// randles_general_rcpp
NumericMatrix randles_general_rcpp(const NumericMatrix& X, bool progress, double tol);
RcppExport SEXP _RandlesID_randles_general_rcpp(SEXP XSEXP, SEXP progressSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(randles_general_rcpp(X, progress, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RandlesID_randles_fast_3d_rcpp", (DL_FUNC) &_RandlesID_randles_fast_3d_rcpp, 2},
    {"_RandlesID_randles_general_rcpp", (DL_FUNC) &_RandlesID_randles_general_rcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_RandlesID(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
