# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

randles_fast_3d_rcpp <- function(X, tol = 1e-10) {
    .Call(`_RandlesID_randles_fast_3d_rcpp`, X, tol)
}

randles_general_rcpp <- function(X, progress = FALSE, tol = 1e-10) {
    .Call(`_RandlesID_randles_general_rcpp`, X, progress, tol)
}

